import {
  BadgeCheck,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CheckCircle2,
  Clock,
  Compass,
  Eye,
  FileCheck2,
  FileText,
  Globe2,
  Handshake,
  HeartHandshake,
  Landmark,
  Lightbulb,
  LineChart,
  LockKeyhole,
  Mail,
  MapPin,
  Network,
  Phone,
  Scale,
  ShieldCheck,
  Target,
  Trophy,
  UsersRound,
} from 'lucide-react';
import type { IconKey } from '../types';

export const iconMap: Record<IconKey, typeof Landmark> = {
  landmark: Landmark,
  handshake: Handshake,
  scale: Scale,
  shield: ShieldCheck,
  globe: Globe2,
  file: FileText,
  target: Target,
  eye: Eye,
  values: Lightbulb,
  compass: Compass,
  users: UsersRound,
  trophy: Trophy,
  lock: LockKeyhole,
  badge: BadgeCheck,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarDays,
  book: BookOpen,
  chart: LineChart,
  network: Network,
  heart: HeartHandshake,
  check: CheckCircle2,
  lightbulb: Lightbulb,
  mail: Mail,
  phone: Phone,
  map: MapPin,
  clock: Clock,
};

export const detailIconMap = {
  education: BookOpen,
  admissions: FileCheck2,
  practices: BriefcaseBusiness,
};
